name: 'Retrieve Posts'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn posts
      - run: yarn build
      - run: yarn postbuild
      - name: commit changes
        uses: EndBug/add-and-commit@v7
