name: 'Retrieve Posts'
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        node-version: '14'
        cache: 'yarn'
      - name: yarn install
        uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      - run: yarn postbuild
      - name: commit changes
        uses: EndBug/add-and-commit@v7
